Update Caste.Core to 4.3.0 * Fix compilation error > MockRepository.cs(213, 17): [CS0618] 'ProxyGenerationOptions.AttributesToAddToGeneratedTypes' is obsolete: 'This property is obsolete and will be removed in future versions. Use AdditionalAttributes property instead. You can use AttributeUtil class to simplify creating CustomAttributeBuilder instances for common cases.'
See details:
* https://github.com/castleproject/Core/blob/master/CHANGELOG.md#400-beta002-2016-10-28
* https://github.com/castleproject/Core/pull/219