Fix warning and compilation error for standard * Assembly level declarative security is obsolete and is no longer enforced by the CLR by default. See http://go.microsoft.com/fwlink/?LinkID=155570 for more information. *  ContextSwitchTests.cs(36, 11): [CS0246] The type or namespace name 'EnvironmentPermissionAttribute' could not be found (are you missing a using directive or an assembly reference?)